### ISSUE TITLE
No longer working CUDA 11.6 is deprecated

### ISSUE THREAD

**Issue by mya2152** [effusiveperiscope/so-vits-svc#12]
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

**Comment by effusiveperiscope** [comment]
Please provide more context
- What OS?
- When does this error occur?

**Comment by cody151** [comment]
> Please provide more context
> 
> - What OS?
> 
> - When does this error occur?
> 
> 

- Google colab "inference" notebook that's listed on the main GitHub page it's being run through connecting to a colab instance

- last night it ran just fine but suddenly the exact same notebook throws up this error now and no longer works all of a sudden

Section where it stops (line15)

#@title Open the file explorer on the left of your screen and drag-and-drop an audio file anywhere. Then run the below cell.
import os
import glob
import json
import copy
import logging
import io
from ipywidgets import widgets
from pathlib import Path
from IPython.display import Audio, display

os.chdir('/content/so-vits-svc')

import torch
from inference import infer_tool
from inference import slicer
from inference.infer_tool import Svc
import soundfile
import numpy as np

MODELS_DIR = "models"

def get_speakers():
  speakers = []
  for _,dirs,_ in os.walk(MODELS_DIR):
    for folder in dirs:
      cur_speaker = {}
      # Look for G_****.pth
      g = glob.glob(os.path.join(MODELS_DIR,folder,'G_*.pth'))
      if not len(g):
        print("Skipping "+folder+", no G_*.pth")
        continue

**Comment by effusiveperiscope** [comment]
This issue should be fixed in the colab notebook; however, it requires restarting the runtime prior to running the final cell.

**Comment by cody151** [comment]
> This issue should be fixed in the colab notebook; however, it requires restarting the runtime prior to running the final cell.

I have restarted it and deleted the current sessions instance but still the error persists, if I run it locally will it work on an AMD gpu?

**Comment by cody151** [comment]
> This issue should be fixed in the colab notebook; however, it requires restarting the runtime prior to running the final cell.

I've also got an M1000M laptop GPU which is an NVIDIA chip but the !nvidia-smi command keeps failing and says can't communicate with the NVIDIA driver?

**Comment by effusiveperiscope** [comment]
Have you refreshed the notebook page (the new version should say something about restarting the runtime)? This has not been tested on AMD. For NVIDIA you may need to update drivers and install CUDA.

**Comment by mya2152** [comment]
> Please provide more context
> 
> * What OS?
> * When does this error occur?

Windows 10 x64
I've fixed it but now it keeps telling me git isn't installed even though it is.

**Comment by effusiveperiscope** [comment]
Are you running through a conda environment? Batch file from .zip release? What specific error message are you getting?

**Comment by mya2152** [comment]
VSCode jupyter notebook extension, inference notebook it's at this step:

#@title Setup HF Downloads (run cell and click buttons to download models)

error:
OSError: Looks like you do not have git installed, please install.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File C:\Python\Python392\lib\site-packages\huggingface_hub\repository.py:569, in Repository.check_git_versions(self)
    568 try:
--> 569     git_version = run_subprocess("git --version", self.local_dir).stdout.strip()
    570 except FileNotFoundError:
File C:\Python\Python392\lib\site-packages\huggingface_hub\utils\_subprocess.py:61, in run_subprocess(command, folder, check, **kwargs)
     59     folder = str(folder)
---> 61 return subprocess.run(
     62     command,
     63     stderr=subprocess.PIPE,
     64     stdout=subprocess.PIPE,
     65     check=check,
     66     encoding="utf-8",
     67     errors="replace",  # if not utf-8, replace char by �
     68     cwd=folder or os.getcwd(),
     69     **kwargs,
     70 )
File C:\Python\Python392\lib\subprocess.py:505, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    503     kwargs['stderr'] = PIPE
--> 505 with Popen(*popenargs, **kwargs) as process:
    506     try:
File C:\Python\Python392\lib\subprocess.py:951, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    948             self.stderr = io.TextIOWrapper(self.stderr,
    949                     encoding=encoding, errors=errors)
--> 951     self._execute_child(args, executable, preexec_fn, close_fds,
    952                         pass_fds, cwd, env,
    953                         startupinfo, creationflags, shell,
    954                         p2cread, p2cwrite,
    955                         c2pread, c2pwrite,
    956                         errread, errwrite,
    957                         restore_signals,
    958                         gid, gids, uid, umask,
    959                         start_new_session)
    960 except:
    961     # Cleanup if the child failed starting.
File C:\Python\Python392\lib\subprocess.py:1420, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)
   1419 try:
-> 1420     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1421                              # no special security
   1422                              None, None,
   1423                              int(not close_fds),
   1424                              creationflags,
   1425                              env,
   1426                              cwd,
   1427                              startupinfo)
   1428 finally:
   1429     # Child is launched. Close the parent's copy of those pipe
   1430     # handles that only the child should have open.  You need
   (...)
   1433     # pipe will not close when the child process exits and the
   1434     # ReadFile will hang.
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:
OSError                                   Traceback (most recent call last)
Cell In[6], line 4
      1 #@title Setup HF Downloads (run cell and click buttons to download models)
      3 from ipywidgets import widgets
----> 4 vul_models = HFModels()
      6 def button_eventhandler(but):
      7   vul_models.download_model(but.description, "models/"+but.description)
Cell In[3], line 139, in HFModels.__init__(self, repo, model_dir)
    137 def __init__(self, repo = "therealvul/so-vits-svc-4.0", 
    138         model_dir = "hf_vul_models"):
--> 139     self.model_repo = huggingface_hub.Repository(local_dir=model_dir,
    140         clone_from=repo, skip_lfs_files=True)
    141     self.repo = repo
    142     self.model_dir = model_dir
File C:\Python\Python392\lib\site-packages\huggingface_hub\utils\_validators.py:120, in validate_hf_hub_args.<locals>._inner_fn(*args, **kwargs)
    117 if check_use_auth_token:
    118     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
--> 120 return fn(*args, **kwargs)
File C:\Python\Python392\lib\site-packages\huggingface_hub\repository.py:504, in Repository.__init__(self, local_dir, clone_from, repo_type, token, git_user, git_email, revision, skip_lfs_files, client)
    501 self.skip_lfs_files = skip_lfs_files
    502 self.client = client if client is not None else HfApi()
--> 504 self.check_git_versions()
    506 if isinstance(token, str):
    507     self.huggingface_token: Optional[str] = token
File C:\Python\Python392\lib\site-packages\huggingface_hub\repository.py:571, in Repository.check_git_versions(self)
    569     git_version = run_subprocess("git --version", self.local_dir).stdout.strip()
    570 except FileNotFoundError:
--> 571     raise EnvironmentError("Looks like you do not have git installed, please install.")
    573 try:
    574     lfs_version = run_subprocess("git-lfs --version", self.local_dir).stdout.strip()
OSError: Looks like you do not have git installed, please install.

//


Any ideas?

**Comment by effusiveperiscope** [comment]
I see. Is git on your PATH? I do not know how Jupyter VSCode interacts with this.

**Comment by mya2152** [comment]
Already added the Git directory into PATH yet the problem persists. I did restart the kernel as well as restarting the entire IDE. What are you using to run notebooks?

**Comment by effusiveperiscope** [comment]
I have only used Colab to run the notebook directly; I have not tested on a local Jupyter platform.

**Comment by effusiveperiscope** [comment]
Upon further research it seems that some additional configuration may be needed to use git from VSCode.
https://stackoverflow.com/questions/29971624/visual-studio-code-cannot-detect-installed-git

Please try the above and see if any of the solutions work for you.

**Comment by mya2152** [comment]
Solved. Many thanks.
